### ISSUE TITLE
Is there a way to specify a custom dockerlint rule

### ISSUE THREAD

**Issue by phlptp** [Lucas-C/pre-commit-hooks-nodejs#7]
Is there a way to specify a custom rule set for dockerfile-lint in pre-commit
My current hook is 
```
- repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
  rev: v1.1.1
  hooks:
  - id: dockerfile_lint
    args: [-r, ./config/Docker/docker_rules.yml]
```
But when run I get a 
```
Error: Dockerfile Dockerfile not found
```
