### ISSUE TITLE
Latest nodejs breaks on ubuntu 18.04

### ISSUE THREAD

**Issue by mambon2** [Lucas-C/pre-commit-hooks-nodejs#9]
https://github.com/nodejs/node/issues/42351
Can you please provide a way to pin this hook to a specific version of nodejs instead of downloading the latest?

**Comment by Lucas-C** [comment]
Have you checked `pre-commit` documentation?
There is already an option to do so:
https://pre-commit.com/#overriding-language-version

**Comment by mambon2** [comment]
> Have you checked `pre-commit` documentation? There is already an option to do so: https://pre-commit.com/#overriding-language-version

I get this error:
```
Updating https://github.com/Lucas-C/pre-commit-hooks-nodejs ... Cannot update because the update target is missing these hooks:
node
```

Here is the code:
```yaml
  - repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
    rev: v1.1.2
    hooks:
      - id: node
        language_version: 16.14.2
```
